export const defaultCSSWidget = {
  containerCSS: {
    width: '100%',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: '#161616',
    borderStyle: 'inherit',
  },
  wrapperCSS: {
    alignItems: 'center',
    alignContent: 'center',
    display: 'flex',
    width: '100%',
    position: 'relative',
  },
};
